# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 662632c8272792f1157e24df7a1b0092dcbb0eec722376279ed7c384bb1beb8dab68eea42095e3f8316c352c26e99e50403920177f167391801e0b2ac3620351

test:
  secret_key_base: cb3d764b30e0975c7b4c59fe21a588a02b43497b23f0767c16e8f5f40060c26ec2eb661ba5b271be480c3887d4d9ddf378cec900712e393ad737b22a52272575

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
